#!/bin/bash

function vscode() {
	docker run \
	-it \
	--rm \
	-e DISPLAY=unix$DISPLAY \
	-e GOPATH=/home/grant/go \
	-v /home/grant/go:/home/grant/go \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	--group-add video \
	--device /dev/dri \
	--device /dev/snd \
	--name code \
	grantseltzer/vscode:v0 \
	zsh
}

vscode
