#!/bin/bash

function slack() {
        docker run \
        --rm \
        --net=host \
        -e DISPLAY=unix$DISPLAY \
        -v $HOME/Downloads:$HOME/Downloads \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        --group-add video \
        --group-add audio \
        --device /dev/dri \
        --device /dev/snd \
        --ipc='host' \
        --name slack \
        grantseltzer/slack:v0 \
        /usr/bin/slack
}

slack
